package com.chenxi.community.model;

public class Notifications {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.ID
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.NOTIFIER
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private String notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.NOTIFIER_NAME
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.RECEIVER
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.OUTERID
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.OUTER_TITLE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private String outerTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.TYPE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATIONS.STATUS
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.ID
     *
     * @return the value of NOTIFICATIONS.ID
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.ID
     *
     * @param id the value for NOTIFICATIONS.ID
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.NOTIFIER
     *
     * @return the value of NOTIFICATIONS.NOTIFIER
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public String getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.NOTIFIER
     *
     * @param notifier the value for NOTIFICATIONS.NOTIFIER
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setNotifier(String notifier) {
        this.notifier = notifier == null ? null : notifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.NOTIFIER_NAME
     *
     * @return the value of NOTIFICATIONS.NOTIFIER_NAME
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.NOTIFIER_NAME
     *
     * @param notifierName the value for NOTIFICATIONS.NOTIFIER_NAME
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.RECEIVER
     *
     * @return the value of NOTIFICATIONS.RECEIVER
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.RECEIVER
     *
     * @param receiver the value for NOTIFICATIONS.RECEIVER
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.OUTERID
     *
     * @return the value of NOTIFICATIONS.OUTERID
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.OUTERID
     *
     * @param outerid the value for NOTIFICATIONS.OUTERID
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.OUTER_TITLE
     *
     * @return the value of NOTIFICATIONS.OUTER_TITLE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.OUTER_TITLE
     *
     * @param outerTitle the value for NOTIFICATIONS.OUTER_TITLE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.TYPE
     *
     * @return the value of NOTIFICATIONS.TYPE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.TYPE
     *
     * @param type the value for NOTIFICATIONS.TYPE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.GMT_CREATE
     *
     * @return the value of NOTIFICATIONS.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.GMT_CREATE
     *
     * @param gmtCreate the value for NOTIFICATIONS.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATIONS.STATUS
     *
     * @return the value of NOTIFICATIONS.STATUS
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATIONS.STATUS
     *
     * @param status the value for NOTIFICATIONS.STATUS
     *
     * @mbg.generated Fri Mar 27 03:41:57 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}